language: node_js
node_js:
    - "5.1"

sudo: required

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
    - npm install -g typescript
    - npm upgrade -g typescript
    - npm install

script:
    - npm run testci
